name: CityBuildPlugin
version: '1.0-SNAPSHOT'
main: net.milocodee.citybuild.CityBuildMain
api-version: '1.21'
commands:
  balance:
    description: Shows your balance
  pay:
    description: Pay money to other players.
  farmwelt:
    description: Teleport zu der Farmwelt.
  plotwelt:
    description: Teleport zur Plotwelt.
  job:
    description: Setze deinen Job.